In [4]:
import numpy as np
import scipy.stats as stats
import matplotlib.pyplot as plt

In [35]:
#风速 v_wind_speed Weibull分布
v_wind_speed_Weibull_distribution=stats.weibull_min.rvs(0.7, 15, size=100)

In [36]:
v_wind_speed_Weibull_distribution

array([15.00140008, 17.05099806, 19.20529308, 16.68428461, 18.14434031,
       15.56029001, 17.99818221, 15.4171214 , 15.40068684, 16.47474819,
       15.72517701, 15.21441518, 18.54350352, 16.35840245, 19.45269947,
       21.93417007, 15.5237138 , 15.99847467, 16.42944201, 16.37652788,
       23.04651045, 16.61596326, 15.01532177, 15.17933951, 15.27711022,
       15.05682788, 16.26806087, 22.92660725, 17.03274928, 15.04616648,
       17.09294882, 15.26905941, 15.13255819, 15.99572948, 17.60611841,
       20.93669446, 15.09117817, 15.42555736, 15.00225977, 15.39489193,
       16.65879025, 15.0178839 , 15.54544812, 15.09935672, 15.40444386,
       17.10034487, 16.45106315, 23.51460735, 16.11527304, 15.01229705,
       15.14180831, 17.58609461, 15.38267556, 15.07204646, 15.0131506 ,
       16.05867963, 15.59884205, 15.02359256, 16.22875164, 16.3503261 ,
       23.24298863, 15.00886974, 15.80135832, 17.35601438, 15.29577163,
       19.93166572, 15.11967121, 15.04440525, 16.15409441, 16.68

In [1]:
import numpy as np
import random

In [2]:
#需求侧用电需求d_power_demand 均匀分布
d_power_demand_uniform_distribution=np.random.uniform(70,80,[1,1000])

In [3]:
d_power_demand_uniform_distribution

array([[74.91539524, 73.34483678, 79.28655605, 77.83452438, 71.90572467,
        75.17033455, 71.96969819, 71.46915874, 70.65240144, 75.76842364,
        74.05372073, 77.33511631, 71.60437161, 79.30819321, 72.80217073,
        74.72768947, 79.35708536, 70.66533714, 76.94183347, 78.87124462,
        77.65028789, 72.62697001, 71.78429346, 73.23455676, 74.51473794,
        70.97550214, 71.61349392, 70.98016961, 74.00740723, 74.3252373 ,
        79.21591111, 78.78345602, 72.55616317, 74.19096731, 76.58478664,
        78.2244124 , 76.5587005 , 74.96894512, 71.33085694, 76.02190884,
        75.45346484, 78.39762505, 73.09056618, 73.08997454, 71.64365468,
        72.69055795, 75.27556722, 70.77055403, 75.77469866, 73.97618771,
        72.79054898, 71.69895783, 73.28318446, 77.45125733, 77.73409257,
        77.56026457, 77.08172713, 76.18650946, 74.91184014, 71.71895799,
        73.50426112, 72.66945993, 71.60543173, 71.72295497, 77.40589128,
        76.63714329, 77.68715264, 73.85473232, 74.2

In [4]:
np.savetxt('./data/d_power_demand_uniform_distribution_[70,80].txt',d_power_demand_uniform_distribution,fmt='%0.8f')

In [54]:
import numpy as np
import random

In [55]:
#需求侧用电需求d_power_demand 高斯分布/正态分布
mu1 = 70  #期望为2
sigma1 = 5  #标准差为0.5
num1 = 2000  #个数为100
d_power_demand_uniform_distribution=np.random.normal(mu1, sigma1, num1)

In [56]:
d_power_demand_uniform_distribution

array([69.89295696, 69.45655576, 68.6429409 , ..., 74.34972802,
       64.43645086, 73.00602025])

In [57]:
np.savetxt('./data/d_power_demand_normal_distribution_(70,5)_2000.txt',d_power_demand_uniform_distribution,fmt='%0.8f')

In [ ]:
#风速分布参数c 均匀分布[3,25]

In [58]:
import numpy as np
import random

In [59]:
c_wind_speed_uniform_distribution=np.random.uniform(3,25,[1,2000])

In [60]:
c_wind_speed_uniform_distribution

array([[ 6.09811447,  3.74630474, 14.79161983, ...,  5.6627305 ,
        22.31096209, 17.3799494 ]])

In [61]:
np.savetxt('./data/c_wind_speed_uniform_distribution_(3,25)_2000.txt',c_wind_speed_uniform_distribution,fmt='%0.8f')

In [ ]:
#风速分布参数c 高斯分布/正态分布 均值15 标准差 2

In [48]:
import numpy as np
import random

In [49]:
#风速分布参数c 高斯分布/正态分布
mu1 = 15  #期望为2
sigma1 = 2  #标准差为0.5
num1 = 1000  #个数为100
c_wind_speed_uniform_distribution=np.random.normal(mu1, sigma1, num1)

In [50]:
c_wind_speed_uniform_distribution

array([15.55207164, 12.21244646, 17.81957999, 12.96092804, 13.60968467,
       18.79157815, 17.19515742, 15.2234281 , 11.22676086, 14.11171245,
       14.78078392, 13.58060018, 12.92499061, 17.12622248, 16.23770723,
       14.1708679 , 16.12064488, 15.70668869, 14.93429405, 12.81201745,
       14.49687276, 11.33834211, 15.89871412, 17.88453623, 17.80258183,
       20.31581157, 12.96315539, 14.3575166 , 13.56200376, 18.89491678,
       12.20533833, 14.745489  , 13.25860488, 11.31421279, 16.37216295,
       12.52090354, 16.5246616 , 12.88471744, 17.84960189, 16.91367513,
       12.99199347, 12.12554526, 12.88435392, 12.53323246, 12.59706805,
       17.72940224, 16.71423606, 18.22593887, 13.79569113, 15.81083695,
       16.44009569, 16.92839512, 16.11748136, 15.65158721, 18.1838831 ,
       14.21292068, 15.52209247, 16.66145125, 17.25904028, 18.17479486,
       13.37401804, 17.24315001, 11.30083181, 14.89782974, 15.74786339,
       14.80429764, 11.66297377, 13.08641511, 14.89057992, 12.37

In [51]:
min(c_wind_speed_uniform_distribution)

8.3734140446088

In [52]:
max(c_wind_speed_uniform_distribution)

21.668514059947512

In [53]:
np.savetxt('./data/c_wind_speed_normal_distribution_(15,2).txt',c_wind_speed_uniform_distribution,fmt='%0.8f')

In [ ]:
#风速分布参数kappa 高斯分布/正态分布 均值2 标准差 0.5

In [42]:
import numpy as np
import random

In [43]:
mu2 = 2  #期望为2
sigma2 = 0.5  #标准差为0.5
num2 = 1000  #个数为100
kappa_wind_speed_uniform_distribution=np.random.normal(mu2, sigma2, num2)

In [44]:
kappa_wind_speed_uniform_distribution

array([2.74579412, 1.78179232, 1.78253006, 2.45202072, 2.13628605,
       1.7956783 , 2.71248447, 1.41882147, 1.61404665, 2.21475831,
       1.49743386, 3.12420233, 1.01030963, 2.8346819 , 2.79139915,
       2.08350736, 2.19702871, 1.92417844, 1.5669346 , 2.13525069,
       2.32045121, 1.97743688, 1.81011681, 1.67783992, 2.52640612,
       1.76773237, 2.7587442 , 1.41077295, 1.82415543, 1.62732011,
       2.2869735 , 1.36576287, 2.03892594, 2.29631676, 2.09918548,
       1.36308404, 2.33145688, 1.74995142, 2.19762523, 2.04649521,
       1.5778784 , 1.74628906, 2.46908323, 1.72987004, 2.89039156,
       1.51006029, 2.73313956, 1.40373308, 1.77816993, 3.57008126,
       2.24312705, 1.54720336, 2.56934829, 2.9934971 , 2.38362737,
       1.28472841, 1.24120636, 1.24132118, 1.35920003, 2.89880158,
       2.60028194, 2.7109753 , 3.11683614, 2.74386859, 2.46640034,
       2.18628163, 3.23974482, 2.3435769 , 2.33341212, 1.72510241,
       1.83366402, 2.02348988, 1.91645779, 2.42535628, 1.52839

In [45]:
min(kappa_wind_speed_uniform_distribution)

0.2262339046470676

In [46]:
max(kappa_wind_speed_uniform_distribution)

3.7920164374538183

In [47]:
np.savetxt('./data/kappa_wind_speed_normal_distribution_(2,0.5).txt',kappa_wind_speed_uniform_distribution,fmt='%0.8f')

In [5]:
#风速分布参数kappa 均匀分布[1,2]

In [62]:
import numpy as np
import random

In [63]:
kappa_wind_speed_uniform_distribution=np.random.uniform(2,3,[1,2000])

In [64]:
kappa_wind_speed_uniform_distribution

array([[2.7965423 , 2.65389888, 2.37236604, ..., 2.22750468, 2.03117183,
        2.59655355]])

In [65]:
np.savetxt('./data/kappa_wind_speed_uniform_distribution_(2,3)_2000.txt',kappa_wind_speed_uniform_distribution,fmt='%0.8f')

In [1]:
import numpy as np
import random

In [2]:
start = 30
end = 120
increment = (end - start) / 1000

numbers = [start + i * increment for i in range(1000)]

print(numbers)

[30.0, 30.09, 30.18, 30.27, 30.36, 30.45, 30.54, 30.63, 30.72, 30.81, 30.9, 30.99, 31.08, 31.17, 31.26, 31.35, 31.44, 31.53, 31.62, 31.71, 31.8, 31.89, 31.98, 32.07, 32.16, 32.25, 32.34, 32.43, 32.52, 32.61, 32.7, 32.79, 32.88, 32.97, 33.06, 33.15, 33.24, 33.33, 33.42, 33.51, 33.6, 33.69, 33.78, 33.87, 33.96, 34.05, 34.14, 34.23, 34.32, 34.41, 34.5, 34.59, 34.68, 34.769999999999996, 34.86, 34.95, 35.04, 35.13, 35.22, 35.31, 35.4, 35.49, 35.58, 35.67, 35.76, 35.85, 35.94, 36.03, 36.12, 36.21, 36.3, 36.39, 36.48, 36.57, 36.66, 36.75, 36.84, 36.93, 37.019999999999996, 37.11, 37.2, 37.29, 37.38, 37.47, 37.56, 37.65, 37.74, 37.83, 37.92, 38.01, 38.1, 38.19, 38.28, 38.37, 38.46, 38.55, 38.64, 38.730000000000004, 38.82, 38.91, 39.0, 39.09, 39.18, 39.269999999999996, 39.36, 39.45, 39.54, 39.629999999999995, 39.72, 39.81, 39.9, 39.99, 40.08, 40.17, 40.26, 40.35, 40.44, 40.53, 40.62, 40.71, 40.8, 40.89, 40.980000000000004, 41.07, 41.16, 41.25, 41.34, 41.43, 41.519999999999996, 41.61, 41.7, 41.79

In [3]:
np.savetxt('./data/d_power_demand_increasing_[30,120].txt',numbers,fmt='%0.8f')

In [ ]:
#生成攻击值

In [ ]:
#小值高斯攻击 均值为-150 

In [8]:
import numpy as np
import random

In [9]:
mu1 = -150  #期望
sigma1 = 5  #标准差
num1 = 1000  #个数为1000
small_Gaussian_Byzantine_attack=np.random.normal(mu1, sigma1, num1)

In [10]:
small_Gaussian_Byzantine_attack

array([-149.59297205, -152.33055808, -147.51183453, -145.00710886,
       -145.87573238, -154.42625175, -163.43373442, -141.96457608,
       -154.16160058, -149.55364001, -148.14055115, -150.06782297,
       -152.45496394, -145.35215795, -142.48595467, -152.22409676,
       -153.10996034, -152.39496363, -146.20768333, -156.03635955,
       -151.5368314 , -148.17079075, -144.37409471, -150.66753933,
       -141.18660551, -145.53643026, -155.52368054, -157.87069272,
       -153.67889617, -149.31267642, -148.41456199, -142.53154216,
       -151.60440327, -147.23689824, -148.22634366, -150.49425491,
       -145.88992903, -154.24329388, -146.26604819, -148.26194036,
       -149.04548139, -145.99577022, -152.39055156, -152.79796576,
       -149.07272545, -145.69625775, -147.62537465, -153.76863862,
       -155.44119583, -153.80884463, -143.16058607, -143.16310446,
       -144.17742657, -151.38419596, -152.95910987, -155.41167026,
       -157.93119141, -147.65523001, -135.09639988, -152.67076

In [11]:
np.savetxt('./data/small_Gaussian_Byzantine_attack_(-150,5).txt',small_Gaussian_Byzantine_attack,fmt='%0.8f')

In [ ]:
#大值高斯攻击 均值为-10 

In [1]:
import numpy as np
import random

In [2]:
mu2 = -10  #期望
sigma2 = 5  #标准差
num2 = 1000  #个数为1000
large_Gaussian_Byzantine_attack=np.random.normal(mu2, sigma2, num2)

In [5]:
large_Gaussian_Byzantine_attack

array([ -4.09660692,  -9.23941845, -14.20669738,  -9.20396922,
       -18.0954435 ,  -5.96549267, -11.65296038, -16.2645874 ,
       -17.09768272, -13.01555695,  -8.6044179 , -15.88658941,
       -10.94763918,  -8.4579762 ,  -8.80487891,  -5.72045939,
       -18.93383069,  -9.79297611,  -7.0281088 ,  -7.41537487,
        -8.75477426,  -7.21969714,  -8.54206195,  -8.18893607,
       -11.28797568,  -8.97148206,  -8.72039781, -10.43346352,
       -16.57515529, -11.53092105, -16.89157044,  -8.73524371,
        -8.47049405, -13.07606569,  -9.99840594, -11.09397655,
       -12.70074705,  -9.02665971,  -5.39951202,  -6.16777251,
        -5.31472133,   0.        ,  -3.53134291,  -6.19514008,
        -0.83826953, -11.4400194 ,  -8.94630051, -10.01412096,
        -1.167592  ,  -4.60734903, -10.27508309,  -8.23193019,
        -4.34130079, -20.02863984, -13.0692722 ,  -9.38001065,
        -7.30521013,  -9.72538596, -14.39901999, -12.76120502,
        -3.51556421, -23.22349427,  -9.62537742, -15.18

In [4]:
for i in range(0,1000):
    if large_Gaussian_Byzantine_attack[i]>0:
        print(large_Gaussian_Byzantine_attack[i])
        large_Gaussian_Byzantine_attack[i]=0

2.7100035530356834
0.07919705052118786
3.616523320574405
0.5081372805763262
0.49328522646443496
0.90202925217746
0.8848325297289978
0.3634691651201649
1.071703651635925
1.561073034482476
1.9223009446161292
0.32116400053126704
0.4081010370107663
6.568782153262582
1.2968979609592868
1.9856387928784276
4.084564857015751
0.81651771573795
8.92288123665352


In [6]:
np.savetxt('./data/large_Gaussian_Byzantine_attack_(-10,5).txt',large_Gaussian_Byzantine_attack,fmt='%0.8f')