In [1]:
import numpy as np
import random

In [2]:
#需求侧用电需求d_power_demand 均匀分布
d_power_demand_uniform_distribution=np.random.uniform(100,120,[1,1000])

In [3]:
d_power_demand_uniform_distribution

array([[106.72780501, 116.60418584, 108.4339008 , 109.83698691,
        112.33157378, 106.67677399, 100.40621768, 119.36806373,
        113.9386592 , 113.6137163 , 115.38425411, 111.45387457,
        112.20851557, 104.37401685, 119.82748581, 111.76203028,
        101.32451294, 101.9200972 , 109.96737097, 114.86147344,
        117.17928645, 107.96029195, 106.82247041, 101.58682337,
        100.613421  , 116.42020889, 104.80819794, 107.96483311,
        116.98419681, 100.34831363, 100.00750901, 101.74555811,
        118.77484712, 112.79896871, 108.93491592, 110.56920511,
        113.76056971, 119.17711371, 113.61825164, 105.18774642,
        109.5106618 , 110.26173299, 101.39080606, 113.08230237,
        102.35806185, 114.53189381, 101.20377879, 105.83124103,
        110.71454332, 117.68298616, 101.04525192, 119.09295857,
        102.52423435, 105.66046915, 115.36277918, 118.99278975,
        109.64761521, 108.44741814, 104.50961625, 105.32478712,
        111.29604001, 119.59321007, 111.

In [4]:
np.savetxt('./data/d_power_demand_uniform_distribution_[100,120].txt',d_power_demand_uniform_distribution,fmt='%0.8f')

In [5]:
import numpy as np
import random

In [8]:
#需求侧用电需求d_power_demand 高斯分布/正态分布
mu1 = 100  #期望为2
sigma1 = 10  #标准差为0.5
num1 = 1000  #个数为100
d_power_demand_normal_distribution=np.random.normal(mu1, sigma1, num1)

In [9]:
d_power_demand_normal_distribution

array([ 78.10342674,  85.73204703,  91.70415949,  92.81865565,
       107.71966101,  82.47730833, 112.85436188,  96.07596744,
       104.39382847,  82.53743152, 107.06139304, 108.1998225 ,
       117.47882024, 111.61664234, 102.13101951, 112.22419289,
       101.7747793 ,  90.70284323, 104.28061595,  82.13934673,
        93.11855282, 130.37825481,  90.07734724, 101.44010435,
       103.9281285 ,  93.44714753,  99.52251178, 111.44347827,
       104.88430859, 104.19200066, 108.96321954, 116.30665364,
       104.26730965,  89.75848214, 107.28616322,  74.87820581,
       112.49753436, 108.42958783,  95.76925834,  92.5131194 ,
       106.14367317, 105.26398981, 104.38622798,  95.51767354,
       127.12604063, 108.56668552, 104.08751806,  99.86353208,
       111.76303562, 115.29130885,  96.15171463,  99.21213343,
        98.30125068,  90.18731936, 104.16304215,  91.74950831,
        99.86666648,  86.89911591, 102.22124039, 114.50575338,
        86.5191172 , 107.9357526 , 110.25053291,  92.60

In [10]:
np.savetxt('./data/d_power_demand_normal_distribution_(100,10).txt',d_power_demand_normal_distribution,fmt='%0.8f')

In [1]:
 import numpy as np
import random

In [2]:
mu1 = -500  #期望
sigma1 = 30  #标准差
num1 = 1000  #个数
large_Gaussian_Byzantine_attack=np.random.normal(mu1, sigma1, num1)

In [3]:
large_Gaussian_Byzantine_attack

array([-481.93548554, -472.60890242, -510.36871263, -490.3609008 ,
       -494.66715772, -488.96628705, -461.28735212, -490.34771078,
       -471.67289935, -498.88894101, -459.98151145, -527.28644204,
       -467.31786368, -447.44928561, -495.47890739, -509.37124761,
       -514.52343667, -579.77919608, -526.57670584, -560.96957063,
       -508.04808254, -476.49606035, -464.35986195, -496.58493102,
       -489.44114718, -526.00472608, -509.7020607 , -510.68182485,
       -467.18795404, -513.15593474, -484.56527493, -491.87890756,
       -500.78728432, -469.22231477, -469.93330295, -454.73376012,
       -513.10960659, -484.56665323, -510.02846519, -515.68758047,
       -471.32091774, -514.47273935, -452.52519575, -451.15868466,
       -537.43897623, -478.57073097, -535.24954536, -435.0760392 ,
       -531.65067617, -511.28692528, -484.43321034, -520.15064906,
       -563.19121524, -511.46705644, -480.16867232, -495.6523879 ,
       -503.32876206, -473.76905509, -519.82435944, -489.10434

In [4]:
np.savetxt('./data/large_Gaussian_Byzantine_attack_(-500,30).txt',large_Gaussian_Byzantine_attack,fmt='%0.8f')

In [1]:
 import numpy as np
import random

In [2]:
mu1 = -1500  #期望
sigma1 = 30  #标准差
num1 = 1000  #个数
small_Gaussian_Byzantine_attack=np.random.normal(mu1, sigma1, num1)

In [3]:
small_Gaussian_Byzantine_attack

array([-1462.97561805, -1482.06916171, -1492.90882383, -1548.8257111 ,
       -1550.41113486, -1482.72775826, -1540.20704049, -1493.68379657,
       -1491.06573472, -1534.15243474, -1498.03169037, -1499.40341025,
       -1594.85338998, -1493.67099856, -1540.74296389, -1517.71160262,
       -1480.80283219, -1494.07507792, -1472.01216791, -1510.43639407,
       -1441.74884563, -1520.42444285, -1527.76307831, -1440.22571793,
       -1486.79584289, -1508.87231858, -1474.29244754, -1498.18264547,
       -1515.33158294, -1461.32939982, -1483.49635401, -1562.62782501,
       -1563.97068774, -1552.70054612, -1501.23999705, -1453.73017673,
       -1531.80658038, -1494.7514645 , -1496.67004921, -1525.54684523,
       -1455.24171714, -1492.83110514, -1545.84028728, -1441.51094943,
       -1539.94277568, -1494.42341894, -1527.92726274, -1509.39204942,
       -1539.19810686, -1512.57359061, -1458.86224402, -1518.81612393,
       -1496.96805438, -1530.67024839, -1484.39258418, -1456.57032053,
      

In [4]:
np.savetxt('./data/small_Gaussian_Byzantine_attack_(-1500,30).txt',small_Gaussian_Byzantine_attack,fmt='%0.8f')